In [2]:
x="hello world"
print(x)

hello world


In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy

In [5]:
a=numpy.array([1,2,3,4,5,6])
print(a)
type(a)

[1 2 3 4 5 6]


numpy.ndarray

In [6]:
import numpy as np
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [7]:
a=np.array([[1,2,3,4,5],[1,2,3,4,5]])
a

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [8]:
a=np.array([[[1,2,3],[1,2,3],[1,2,3]]])
print(a)

[[[1 2 3]
  [1 2 3]
  [1 2 3]]]


In [9]:
a=np.array([[1,2,3],[4,5,6]])
print(a.ndim)

2


In [10]:
a=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(a.ndim)

3


In [11]:
a=np.array([1,2,3],ndmin=6)
print(a)

[[[[[[1 2 3]]]]]]


In [12]:
a=np.array([1,2,3])
b=np.array([[2,3,4],[3,4,5]])
c=np.array([[[3,4,5],[2,3,4]],[[4,5,6],[1,2,3]]])
print(a.shape)
print(b.shape)
print(c.shape)

(3,)
(2, 3)
(2, 2, 3)


In [13]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(a.reshape(2,3,2))
a

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [14]:
a=np.array([["a","b","c","d"]])
b=np.array([["e","f","g","h"]])
print(a)
print(b)
c=np.concatenate((a,b))
print(c)

[['a' 'b' 'c' 'd']]
[['e' 'f' 'g' 'h']]
[['a' 'b' 'c' 'd']
 ['e' 'f' 'g' 'h']]


In [15]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.concatenate((a,b))
print(c)

[1 2 3 4 5 6]


In [16]:
x=np.array([1,2,3])
y=np.array([4,5,6])
c=np.stack((a,b))
print(c)

[[1 2 3]
 [4 5 6]]


In [17]:
x=np.array([[1,2,3],[4,5,6]])
y=np.array([[7,8,9],[10,11,12]])
z=np.stack((x,y))
print(z)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [18]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.stack((a,b))
print(c)

[[1 2 3]
 [4 5 6]]


In [19]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.hstack((a,b))
print(c)

[1 2 3 4 5 6]


In [20]:
a=np.array([[1,2,3],[7,8,9]])
b=np.array([[4,5,6],[10,11,12]])
c=np.hstack((a,b))
print(c)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [21]:
a=np.array([[[1,2,3],[7,8,9],[10,11,12]]])
b=np.array([[[4,5,6],[13,14,15],[16,17,18]]])
c=np.hstack((a,b))
print(c)

[[[ 1  2  3]
  [ 7  8  9]
  [10 11 12]
  [ 4  5  6]
  [13 14 15]
  [16 17 18]]]


In [22]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.vstack((a,b))
print(c)

[[1 2 3]
 [4 5 6]]


In [23]:
a=np.array([[1,2],[3,6]])
b=np.array([[4,5],[7,8]])
c=np.vstack((a,b))
print(c)

[[1 2]
 [3 6]
 [4 5]
 [7 8]]


In [24]:
a=np.array([[1,2],[3,6],[7,8]])
b=np.array([[4,5],[9,10],[11,12]])
c=np.vstack((a,b))
print(c)

[[ 1  2]
 [ 3  6]
 [ 7  8]
 [ 4  5]
 [ 9 10]
 [11 12]]


In [25]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.dstack((a,b))
print(c)

[[[1 4]
  [2 5]
  [3 6]]]


In [26]:
a=np.array([[1,2,3],[7,8,9]])
b=np.array([[4,5,6],[10,11,12]])
c=np.dstack((a,b))
print(c)

[[[ 1  4]
  [ 2  5]
  [ 3  6]]

 [[ 7 10]
  [ 8 11]
  [ 9 12]]]


In [27]:
a=np.array([[[1,2,3],[7,8,9],[10,11,12]]])
b=np.array([[[4,5,6],[13,14,15],[16,17,18]]])
c=np.dstack((a,b))
print(c)

[[[ 1  2  3  4  5  6]
  [ 7  8  9 13 14 15]
  [10 11 12 16 17 18]]]


In [28]:
a=np.array([1,2,3,4])
c=np.array_split(a,2)
print(c)

[array([1, 2]), array([3, 4])]


In [29]:
a=np.array([[1,2,3,4],[5,6,7,8]])
c=np.array_split(a,2)
print(c)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]


In [30]:
a=np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
c=np.array_split(a,2,2)
print(c)

[array([[[ 1,  2],
        [ 5,  6],
        [ 9, 10]]]), array([[[ 3,  4],
        [ 7,  8],
        [11, 12]]])]


In [31]:
n=np.zeros(4)
print(n)

[0. 0. 0. 0.]


In [32]:
n=np.zeros((2,2))
print(n)

[[0. 0.]
 [0. 0.]]


In [33]:
n=np.zeros((2,2,2))
print(n)

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [34]:
n=np.ones((2,2,2))
print(n)

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


In [39]:
n=np.ones((2,3))
print(n)

[[1. 1. 1.]
 [1. 1. 1.]]


In [42]:
n=np.arange(10)
print(n)

[0 1 2 3 4 5 6 7 8 9]


In [43]:
n=np.arange(10,20,3)
print(n)

[10 13 16 19]


In [47]:
n=np.linspace(10,20,5)
print(n)

[10.  12.5 15.  17.5 20. ]


In [48]:
n=np.eye(5,8)
print(n)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]]


In [49]:
n=np.full(2,6)
print(n)

[6 6]


In [50]:
a=np.full(5,8)
print(a)

[8 8 8 8 8]


In [58]:
n=np.full((2,4),5)
print(n)

[[5 5 5 5]
 [5 5 5 5]]


In [64]:
n=np.full((3,4,6),5)
print(n)

[[[5 5 5 5 5 5]
  [5 5 5 5 5 5]
  [5 5 5 5 5 5]
  [5 5 5 5 5 5]]

 [[5 5 5 5 5 5]
  [5 5 5 5 5 5]
  [5 5 5 5 5 5]
  [5 5 5 5 5 5]]

 [[5 5 5 5 5 5]
  [5 5 5 5 5 5]
  [5 5 5 5 5 5]
  [5 5 5 5 5 5]]]


In [63]:
n=np.full((2,3,4),5)
print(n)

[[[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]

 [[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]]


In [66]:
a=np.full((2,3,4),2)
print(a)

[[[2 2 2 2]
  [2 2 2 2]
  [2 2 2 2]]

 [[2 2 2 2]
  [2 2 2 2]
  [2 2 2 2]]]


In [73]:
n=np.random.randint(2,5,8)
print(n)

[3 4 4 2 2 2 3 2]


In [76]:
a=np.random.randint(10,20,(2,9))
print(a)

[[10 19 12 10 17 11 16 15 10]
 [12 16 14 15 11 15 18 13 14]]


In [78]:
a=np.random.randint(5,10,(3,9,3))
print(a)

[[[5 6 5]
  [7 6 9]
  [6 5 6]
  [6 5 7]
  [7 9 8]
  [8 6 5]
  [9 6 8]
  [7 9 6]
  [6 8 5]]

 [[5 7 5]
  [8 7 5]
  [7 8 8]
  [8 6 6]
  [9 9 9]
  [5 6 6]
  [6 7 7]
  [9 8 9]
  [5 9 6]]

 [[7 6 7]
  [6 9 6]
  [9 9 5]
  [5 7 9]
  [7 8 6]
  [8 5 8]
  [7 9 6]
  [8 6 9]
  [7 6 9]]]


In [79]:
n=np.random.random(5)
print(n)

[0.21165432 0.84491174 0.107776   0.28209718 0.09686736]


In [80]:
a=np.random.random(3)
print(a)

[0.4627696  0.62041692 0.67116616]
